config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resource :eyny_downloader, :only=>[:show], to: "eyny_downloader#index" do
    post :download, to: "eyny_downloader#download"
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eyny_downloader.rb
require 'nokogiri'
require 'open-uri'

class EynyDownloader < ApplicationRecord
  attr_reader :result, :target, :filename, :download_path
  def load(url)
    pre_web = URI::escape(url.to_s)
    web = Nokogiri::HTML(open(pre_web))
    source_tag = web.css('div#video_container video#mediaplayer source').first
    if source_tag
      @target = source_tag.attribute('src').to_s
    else
      @target = nil
    end
  end
  def download(url, name)
    @filename = name.to_s + ".mp4"
    @download_path = File.join(Rails.root, 'public', filename)
    system_command = "wget -O #{download_path} #{url}"
    @result = system(system_command)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eyny_downloader_controller.rb
class EynyDownloaderController < ApplicationController
  def index
    @downloader = EynyDownloader.new
  end
  def download
    @downloader = EynyDownloader.new
    target = @downloader.load(params[:eyny_downloader][:url])
    @downloader.download(target, params[:eyny_downloader][:filename])
    if @downloader.result
      sent_to_user
    else
      redirect_to eyny_downloader_path
    end
  end
  def sent_to_user
    data = open(@downloader.download_path)
    send_data(data.read, filename: @downloader.filename)
    File.delete(@downloader.download_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eyny_downloader_helper.rb
module EynyDownloaderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/eyny_downloader/index.html.erb
<br />
<h1>伊莉影片下載器～</h1><br />
<p>請將點開後有影片的網址複製至下方欄位，並命名主檔名。</p><br />

<%= form_for(@downloader, url: download_eyny_downloader_path) do |f| %>
  <%= f.label :url, "網址" %>
  <%= f.text_area :url, class: "form-control" %><br />

  <%= f.label :filename, "主檔名" %>
  <%= f.text_field :filename, class: "form-control" %><br />

  <%= f.submit "下載", class: "btn btn-success"%><br /><br />

  <p>下載成功後，請重新整理或回首頁</p>

<% end %>

<%= link_to "回首頁", root_path, class: "btn btn-info" %>

app/views/home/index.html.erb
<h1>各種地方的小小下載器～</h1><br />
<h3>伊莉影片下載器</h3>
<%= link_to "GO", eyny_downloader_path, class: "btn btn-success" %><br />
<h3>Pinterest下載器</h3>
<%= link_to "GO", root_path, class: "btn btn-success" %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Downloader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>